stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    outs:
    - data/raw
  train_model:
    cmd: python src/train_model.py
    deps:
    - src/train_model.py
    params:
    - train.random_state
    - train.test_size
    outs:
    - models/model.pkl
  evaluate_model:
    cmd: python src/evaluate_model.py
    deps:
    - models/model.pkl
    - src/evaluate_model.py
    metrics:
    - metrics.txt:
        cache: false
  predict:
    cmd: python src/predict.py
    deps:
    - data/raw/test.csv
    - models/model.pkl
    - src/predict.py
    outs:
    - outputs/predictions.csv
